import { Inter } from "next/font/google";
import {Open_Sans} from "next/font/google";
import {Dosis} from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const openSans = Open_Sans({
  weight: '700',
  subsets: ['latin'],
})

const oswald = Dosis({
  weight: '700',
  subsets: ['latin'],
})

export const metadata = {
  title: "Isaac Renovations Pro Corp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
    </html>
  );
}
